export const USER_FOLLOW_DATA_LOAD = 'user/FOLLOW_DATA_LOAD';
export const FOLLOWERS_UPDATE_FOLLOW = 'followers/UPDATE_FOLLOW';

export const FOLLOWERS_GET_FOLLOWERS = 'followers/GET_FOLLOWERS';
export const FOLLOWERS_GET_FOLLOWERS_SUCCESS = 'followers/GET_FOLLOWERS_SUCCESS';
export const FOLLOWERS_GET_FOLLOWERS_ERROR = 'followers/GET_FOLLOWERS_ERROR';

export const FOLLOWERS_GET_FOLLOWING = 'followers/GET_FOLLOWING';
export const FOLLOWERS_GET_FOLLOWING_SUCCESS = 'followers/GET_FOLLOWING_SUCCESS';
export const FOLLOWERS_GET_FOLLOWING_ERROR = 'followers/GET_FOLLOWING_ERROR';
