export const NOTIFICATION_ONLINE_ADD_NOTIFICATION = 'notificationsOnline/ADD_NOTIFICATION';

export const NOTIFICATION_ONLINE_GET_HISTORY = 'notificationsOnline/GET_HISTORY';
export const NOTIFICATION_ONLINE_GET_HISTORY_SUCCESS = 'notificationsOnline/GET_HISTORY_SUCCESS';
export const NOTIFICATION_ONLINE_GET_HISTORY_ERROR = 'notificationsOnline/GET_HISTORY_ERROR';

export const NOTIFICATION_ONLINE_GET_HISTORY_FRESH = 'notificationsOnline/GET_HISTORY_FRESH';
export const NOTIFICATION_ONLINE_GET_HISTORY_FRESH_SUCCESS =
    'notificationsOnline/GET_HISTORY_FRESH_SUCCESS';
export const NOTIFICATION_ONLINE_GET_HISTORY_FRESH_ERROR =
    'notificationsOnline/GET_HISTORY_FRESH_ERROR';
