export const NOTIFICATION_GET_HISTORY = 'notifications/GET_HISTORY';
export const NOTIFICATION_GET_HISTORY_SUCCESS = 'notifications/GET_HISTORY_SUCCESS';
export const NOTIFICATION_GET_HISTORY_ERROR = 'notifications/GET_HISTORY_ERROR';

export const NOTIFICATION_GET_HISTORY_FRESH = 'notifications/GET_HISTORY_FRESH';
export const NOTIFICATION_GET_HISTORY_FRESH_SUCCESS = 'notifications/GET_HISTORY_FRESH_SUCCESS';
export const NOTIFICATION_GET_HISTORY_FRESH_ERROR = 'notifications/GET_HISTORY_FRESH_ERROR';
