export const UI_COMMON_SAVE_SCROLL_POSITION = 'ui/common/SAVE_SCROLL_POSITION';

export const UI_LOCATION_CHANGED = 'ui/location/LOCATION_CHANGED';

export const UI_PROFILE_CHANGE_LAYOUT = 'ui/profile/CHANGE_LAYOUT';
export const UI_PROFILE_ACTIVITY_CHANGE_TAB = 'ui/profile/activity/CHANGE_TAB';

export const UI_HOME_TAGS_CARD_COLLAPSE = 'ui/home/tagsCard/COLLAPSE';
export const UI_ON_BACK_CLICK = 'ui/ON_BACK_CLICK';

export const UI_TOGGLE_COMMENT_INPUT_FOCUS = 'ui/TOGGLE_COMMENT_INPUT_FOCUS';

export const UI_SET_WALLET_TAB_STATE = 'ui/SET_WALLET_TAB_STATE';
export const UI_SET_WALLET_TABS_STATE = 'ui/SET_WALLET_TABS_STATE';
