export const FETCH_WITNESS_DATA = 'user/FETCH_WITNESS_DATA';
export const FETCH_WITNESS_DATA_SUCCESS = 'user/FETCH_WITNESS_DATA_SUCCESS';
export const FETCH_WITNESS_DATA_ERROR = 'user/FETCH_WITNESS_DATA_ERROR';
