export const SHOW_VOTED_USERS = 'dialog/SHOW_VOTED';
export const GET_VOTERS_USERS_REQUEST = 'global/GET_VOTERS_REQUEST';
export const GET_VOTERS_USERS_SUCCESS = 'global/GET_VOTERS_USERS_SUCCESS';
export const GET_VOTERS_USERS_ERROR = 'global/GET_VOTERS_ERROR';
