export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';

export const VOTE_POST = 'VOTE_POST';
export const VOTE_POST_SUCCESS = 'VOTE_POST_SUCCESS';
export const VOTE_POST_ERROR = 'VOTE_POST_ERROR';

export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';

export const FETCH_POST_COMMENTS = 'FETCH_POST_COMMENTS';
export const FETCH_POST_COMMENTS_SUCCESS = 'FETCH_POST_COMMENTS_SUCCESS';
export const FETCH_POST_COMMENTS_ERROR = 'FETCH_POST_COMMENTS_ERROR';

export const FETCH_FEED_COMMENTS = 'FETCH_FEED_COMMENTS';
export const FETCH_FEED_COMMENTS_SUCCESS = 'FETCH_FEED_COMMENTS_SUCCESS';
export const FETCH_FEED_COMMENTS_ERROR = 'FETCH_FEED_COMMENTS_ERROR';

export const UPDATE_UI_MODE = 'UPDATE_UI_MODE';

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const GATE_AUTHORIZE_SECRET = 'GATE_AUTHORIZE_SECRET';
export const GATE_AUTHORIZE_SECRET_SUCCESS = 'GATE_AUTHORIZE_SECRET_SUCCESS';
export const GATE_AUTHORIZE_SECRET_ERROR = 'GATE_AUTHORIZE_SECRET_ERROR';

export const GATE_AUTHORIZE = 'GATE_AUTHORIZE';
export const GATE_AUTHORIZE_SUCCESS = 'GATE_AUTHORIZE_SUCCESS';
export const GATE_AUTHORIZE_ERROR = 'GATE_AUTHORIZE_ERROR';

export const SET_SERVER_ACCOUNT_NAME = 'SET_SERVER_ACCOUNT_NAME';

export const SET_COMMENTS_FILTER = 'SET_COMMENTS_FILTER';

export const PROVIDE_BW = 'PROVIDE_BW';
export const PROVIDE_BW_SUCCESS = 'PROVIDE_BW_SUCCESS';
export const PROVIDE_BW_ERROR = 'PROVIDE_BW_ERROR';

export const UPDATE_PROFILE_DATA = 'UPDATE_PROFILE_DATA';
export const UPDATE_PROFILE_DATA_SUCCESS = 'UPDATE_PROFILE_DATA_SUCCESS';
export const UPDATE_PROFILE_DATA_ERROR = 'UPDATE_PROFILE_DATA_ERROR';

export const FETCH_EMBED = 'FETCH_EMBED';
export const FETCH_EMBED_SUCCESS = 'FETCH_EMBED_SUCCESS';
export const FETCH_EMBED_ERROR = 'FETCH_EMBED_ERROR';

/* for registration */
export const SET_SCREEN_ID = 'SET_SCREEN_ID';
export const SET_PHONE_NUMBER = 'SET_PHONE_NUMBER';
export const SET_LOC_DATA = 'SET_LOC_DATA';
export const SET_WISH_USERNAME = 'SET_WISH_USERNAME';
export const CLEAN_REGISTRATION_DATA = 'CLEAN_REGISTRATION_DATA';

export const FETCH_REG_STATE = 'FETCH_REG_STATE';
export const FETCH_REG_STATE_SUCCESS = 'FETCH_REG_STATE_SUCCESS';
export const FETCH_REG_STATE_ERROR = 'FETCH_REG_STATE_ERROR';

export const SET_POST_VOTE = 'SET_POST_VOTE';
export const SET_COMMENT_VOTE = 'SET_COMMENT_VOTE';

export const PIN_COMMUNITY = 'PIN_COMMUNITY';
export const PIN_COMMUNITY_SUCCESS = 'PIN_COMMUNITY_SUCCESS';
export const PIN_COMMUNITY_ERROR = 'PIN_COMMUNITY_ERROR';

export const UNPIN_COMMUNITY = 'UNPIN_COMMUNITY';
export const UNPIN_COMMUNITY_SUCCESS = 'UNPIN_COMMUNITY_SUCCESS';
export const UNPIN_COMMUNITY_ERROR = 'UNPIN_COMMUNITY_ERROR';

export const BLOCK_USER = 'BLOCK_USER';
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS';
export const BLOCK_USER_ERROR = 'BLOCK_USER_ERROR';

export const UNBLOCK_USER = 'UNBLOCK_USER';
export const UNBLOCK_USER_SUCCESS = 'UNBLOCK_USER_SUCCESS';
export const UNBLOCK_USER_ERROR = 'UNBLOCK_USER_ERROR';

export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_ERROR = 'FETCH_NOTIFICATIONS_ERROR';

export const CALL_MARK_ALL_AS_VIEWED = 'CALL_MARK_ALL_AS_VIEWED';
export const CALL_MARK_ALL_AS_VIEWED_SUCCESS = 'CALL_MARK_ALL_AS_VIEWED_SUCCESS';
export const CALL_MARK_ALL_AS_VIEWED_ERROR = 'CALL_MARK_ALL_AS_VIEWED_ERROR';

export const CALL_MARK_AS_VIEWED = 'CALL_MARK_AS_VIEWED';
export const CALL_MARK_AS_VIEWED_SUCCESS = 'CALL_MARK_AS_VIEWED_SUCCESS';
export const CALL_MARK_AS_VIEWED_ERROR = 'CALL_MARK_AS_VIEWED_ERROR';
