export const MODAL_CONFIRM = 'MODAL_CONFIRM';
export const MODAL_CANCEL = 'MODAL_CANCEL';

export const MODAL_LOGIN = 'MODAL_LOGIN';
export const MODAL_SIGNUP = 'MODAL_SIGNUP';
export const MODAL_PROFILE_ABOUT_EDIT = 'MODAL_PROFILE_ABOUT_EDIT';
export const MODAL_SEND_POINTS = 'MODAL_SEND_POINTS';
export const MODAL_POST = 'MODAL_POST';

export const OPENED_FROM_LOGIN = 'OPENED_FROM_LOGIN';
