export const CONTACTS_SEARCH = 'contacts/SEARCH';
export const CONTACTS_SEARCH_SUCCESS = 'contacts/SEARCH_SUCCESS';

export const CONTACTS_GET_CONTACTS_LIST_SIZE = 'contacts/GET_CONTACTS_LIST_SIZE';
export const CONTACTS_GET_CONTACTS_LIST_SIZE_SUCCESS = 'contacts/GET_CONTACTS_LIST_SIZE_SUCCESS';

export const CONTACTS_GET_CONTACTS_LIST = 'contacts/GET_CONTACTS_LIST_SUCCESS';
export const CONTACTS_GET_CONTACTS_LIST_SUCCESS = 'contacts/GET_CONTACT_LISTS_SUCCESS';
